---
language: python
python: "2.7"

before_install:
  - sudo apt-get update --assume-yes -qq
  - sudo apt-get install --assume-yes -qq python-apt python-pycurl

install:
  # Install Ansible
  - sudo pip install ansible

  # Add ansible.cfg to pick up roles path
  #  - "echo -en  '[defaults]\nroles_path = ../' > ansible.cfg"
  #- cat ansible.cfg
  - cp tests/ansible.cfg ./

script:
  - ansible --version
  # Check the role/playbook's syntax
  - ansible-playbook --inventory-file tests/hosts --syntax-check tests/playbook.yml
  # Run the role/playbook with ansible-playbook
  - ansible-playbook --inventory-file tests/hosts --connection=local --sudo -vvvv tests/playbook.yml
  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook --inventory-file tests/hosts --connection=local --sudo tests/playbook.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
