---
# handlers file for iptables

- name: restart iptables
  service:
    name: "{{ iptables__service_name }}"
    state: restarted

- name: restart knockd
  service:
    name: "{{ knockd__service_name }}"
    state: restarted
